In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("/Users/terrychen/Desktop/Group_of_machine_learning/Terry_Directory/Data/Merege_data_with_Sasha/movies_features_with_social_Metadata_with_log.csv", sep = ',', header = 'infer')

,tconst,primaryTitle,startYear,averageRating,numVotes,genre_score,movie_writer_quality,movie_actor_score,budget,director_quality,top_3_actor_scores,log_top3_fb
0,tt10103028,Blindfire,2020,4.9,807,5.934379,4.9,6.312799,2.541177e+07,4.9,930.333333,6.836617

In [9]:
raw_socail_data = pd.read_csv("/Users/terrychen/Desktop/Group_of_machine_learning/Terry_Directory/Data/NYC_acdamic_datasets/movie_metadata.csv", sep = ',', header = 'infer')

In [10]:
raw_socail_data.head(5)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [14]:
raw_socail_data.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [15]:
raw_socail_data[['movie_title', 'actor_1_name', 'actor_1_facebook_likes',
                 'actor_2_name', 'actor_2_facebook_likes',
                 'actor_3_name', 'actor_3_facebook_likes']].head(5)

,movie_title,actor_1_name,actor_1_facebook_likes,actor_2_name,actor_2_facebook_likes,actor_3_name,actor_3_facebook_likes
0,Avatar,CCH Pounder,1000.0,Joel David Moore,936.0,Wes Studi,855.0
1,Pirates of the Caribbean: At World's End,Johnny Depp,40000.0,Orlando Bloom,5000.0,Jack Davenport,1000.0
2,Spectre,Christoph Waltz,11000.0,Rory Kinnear,393.0,Stephanie Sigman,161.0
3,The Dark Knight Rises,Tom Hardy,27000.0,Christian Bale,23000.0,Joseph Gordon-Levitt,23000.0
4,Star Wars: Episode VII - The Force Awakens ...,Doug Walker,131.0,Rob Walker,12.0,NaN,NaN

In [16]:
raw_socail_data[[ 'actor_1_facebook_likes',
                'actor_2_facebook_likes',
                 'actor_3_facebook_likes']].describe()

       actor_1_facebook_likes  actor_2_facebook_likes  actor_3_facebook_likes
count             5036.000000             5030.000000             5020.000000
mean              6560.047061             1651.754473              645.009761
std              15020.759120             4042.438863             1665.041728
min                  0.000000                0.000000                0.000000
25%                614.000000              281.000000              133.000000
50%                988.000000              595.000000              371.500000
75%              11000.000000              918.000000              636.000000
max             640000.000000           137000.000000            23000.000000

In [2]:
df.head(5)

,tconst,primaryTitle,startYear,averageRating,numVotes,genre_score,movie_writer_quality,movie_actor_score,budget,director_quality,top_3_actor_scores,log_top3_fb
0,tt10103028,Blindfire,2020,4.9,807,5.934379,4.900000,6.312799,2.541177e+07,4.900000,930.333333,6.836617
1,tt29173358,BJJ: Woman on Top,2023,4.3,143,6.222951,4.775000,5.584329,2.244917e+07,4.950000,15333.333333,9.637850
2,tt10276160,Weekend,2020,4.8,311,5.914762,4.800000,6.594587,2.553168e+07,4.800000,3851.333333,8.256434
3,tt20511498,Plancha,2022,5.4,702,5.885894,5.350000,6.509762,2.828938e+07,5.350000,24333.333333,10.099644
4,tt13575922,Cheeni,2020,6.4,786,6.222951,6.562024,7.932981,2.244917e+07,6.733333,71.500000,4.283587

In [4]:
df.shape

(5010, 12)

In [5]:
df.columns.tolist()

['tconst',
 'primaryTitle',
 'startYear',
 'averageRating',
 'numVotes',
 'genre_score',
 'movie_writer_quality',
 'movie_actor_score',
 'budget',
 'director_quality',
 'top_3_actor_scores',
 'log_top3_fb']